## Jest로 함수 단위 테스트하기

저번 2주차 피드백을 통해 이번 3주차에서는 지난 과제에서 미흡했던 부분을 보완하자고 다짐했다.

저번 과제에서 Jest를 활용한 테스트를 많이 해보지 못해서 이번 과제를 할 때는 함수(메서드)를 한 가지 일만 잘 하도록 나누고 꼭 단위 테스팅을 해야겠다고 생각했다.

그래서 이번 과제는 메서드를 먼저 한 가지 일만 잘 하도록 잘게 쪼개고,

각 클래스의 메서드 단위로 테스트를 진행했다.

`Validator` 클래스에는 유효성을 검사하는 메서드가 존재한다.

```jsx
class Validator {
  ...
  validateNumber(money) {
    const check = /^[0-9]+$/;
    if (!check.test(money)) throw Error(ERROR_MESSAGES.type);
    return true;
  }
  ...
}

module.exports = Validator;
```

`validateNumber` 메서드는 로또 구입 금액을 입력 받으면 해당 입력값이 숫자로 되어 있는지 검사한다.

`validateNumber` 메서드에 대한 테스팅을 `ValidatorTest.js` 에서 수행한다.

```jsx
describe('유효성 검사 클래스 메서드 테스트', () => {
  test('구입 금액 입력 시 숫자로 된 값이 아니면 타입 에러가 발생한다.', () => {
    expect(() => {
      const validator = new Validator();
      const money = '1000a';
      validator.validateNumber(money);
    }).toThrow(ERROR_MESSAGES.type);
  });
  ...
}
```
![image](https://user-images.githubusercontent.com/62415600/201535874-c3c0eedf-5e09-4171-a983-5a8ad25cd6cb.png)


***vscode-extension***의 `Jest` 를 활용해서 함수 단위로 쉽게 테스트할 수 있었다.
![image](https://user-images.githubusercontent.com/62415600/201535930-41229683-d966-4ca7-bef4-2a1d2712e237.png)


만약 `validateNumber` 메서드가 반환하는 에러 메시지를 타입이 아닌 입력값의 길이에 대한 내용으로 바꾸면?

```jsx
validateNumber(money) {
    const check = /^[0-9]+$/;
    if (!check.test(money)) throw Error(ERROR_MESSAGES.length);
    return true;
  }
```

빨간줄 찍 긋고 아래와 같이 에러를 띄운다. 

![image](https://user-images.githubusercontent.com/62415600/201535857-a1d16ae9-0401-4f5b-9ed6-24871f1330d8.png)

입력값이 숫자인지 검증하는 메서드라서,
Jest는 반환하는 에러 메시지가 ***“[ERROR] 입력 금액은 숫자여야 합니다.”*** 를 예상했지만 반환 받은 메시지가 다르다는걸 보여준다.

![image](https://user-images.githubusercontent.com/62415600/201535848-f3b446cd-8a3e-4572-8cb2-7359475ad9ad.png)

이렇게 함수 단위로 테스트하며 3주차 과제를 구현하면서 느낀 점이 많았다.

과제를 구현하면서 예상치 못한 에러가 애초에 덜 발생하고, 
에러가 발생해도 핸들링하기 한결 수월하다고 생각했다.

또한 함수 단위로 테스팅하기 위한 전제조건은 함수가 한 가지 일만 잘 하도록 잘게 나누는 것인데, 이번 과제에서는 함수가 정말 한 가지 일만 하게 나누려고 노력했다.

그렇게 차근차근 구현하다가 기존 `App` 클래스에 도메인 로직과 UI 담당 메서드가 함께 공존하던 것에서, `App` 클래스에는 UI(입출력)를 담당하는 메서드만 남기고 도메인 로직을 따로 분리해서 `Purchaser` 클래스에 분담하는 리팩터링을 진행했다.

하나의 클래스에 공존하던 메서드를 다른 클래스로 분리하면 필연적으로 에러가 발생한다. 그래서 도메인 로직을 분리하기 전에 걱정이 앞섰다. 하지만 함수 단위로 테스팅을 진행하며 구현하고 있었기에 에러 핸들링이 할만할 거라고 생각했고 그대로 리팩터링을 시작했다. 

```jsx
// UI를 담당하는 App 클래스 예시
class App {
  ...
  play() {
    this.inputMoney();
  }

  inputMoney() {
    Console.readLine(INPUT_MESSAGES.money, (money) => {
      this.validator.validateInput(money);
      this.purchaser = new Purchaser(money);
      this.#lottos = this.purchaser.buyLotto(money / 1000);
      this.showLottoNumber();
      this.inputWinnerNumber();
    });
  }

  showLottoNumber() {
    Console.print(`${this.#lottos.length}${MESSAGES.purchase}`);
    this.#lottos.forEach((lotto) =>
      Console.print(`[${lotto.getNumbers().join(', ')}]`)
    );
  }
  ...
  }
}

// 도메인 로직을 담당하는 Purchaser 클래스 예시
class Purchaser {
  ...
  buyLotto(number) {
    const tokens = this.createToken(number);
    const lottos = tokens.map((token) => new Lotto(token));
    return lottos;
  }

  createToken(number) {
    const numberGenerator = new NumberGenerator();
    const tokens = [];
    let count = 0;
    while (count < number) {
      tokens.push(numberGenerator.pickRandomNumbers().sort((a, b) => a - b));
      count += 1;
    }
    return tokens;
  }

  countMatchedNumber(lottos, winnerNumber, bonusNumber) {
    let matchedCountList = [0, 0, 0, 0, 0, 0, 0, 0];
    lottos.forEach((lotto) => {
      const { count, bonus } = this.compare(
        lotto.getNumbers(),
        winnerNumber,
        bonusNumber
      );
      matchedCountList = [
        ...this.computeMatchingNumber(count, bonus, matchedCountList),
      ];
    });
    return matchedCountList;
  }

  compare(lottoToken, winnerNumber, bonusNumber) {
    let count = 0;
    const bonus = lottoToken.includes(bonusNumber) ? 1 : 0;

    count = 0;
    count = winnerNumber.reduce(
      (acc, cur) => (acc += lottoToken.includes(cur) ? 1 : 0),
      0
    );
    return { count, bonus };
  }
  ...
}
```

위와 같이 하나의 클래스를 각자의 역할에 맞게 두 개의 클래스로 분리했다.

예상했던 에러를 막기 위해 먼저 기존 `App` 메서드 내부에서 호출했던 메서드의 `this` 를 바꿔주었다.

그리고 테스트를 진행했는데 에러가 하나도 발생하지 않는 것이다!

솔직히 정말 놀라웠다. 

그동안 혼자 공부하면서 함수를 작성하고 전체적인 구조를 바꾸던 작업은 정말 에러 천지투성이였다.

저번 피드백을 머릿속에 떠올리며 3주차 과제를 진행했다.

> “**함수가 하나의 일만 잘 하도록 분리하고 각 함수에 대해 테스팅을 진행하자”**
> 

함수 단위로 테스트하며 구현하고 있었기에 에러가 마구마구 튀어나올 거라고 생각하진 않았지만 생각보다 너무 깔끔하게 리팩터링을 할 수 있었다.

솔직히 처음에는 함수 단위 테스팅에 대해 회의적이었다. 정말 귀찮은 작업이라 치부했는데, 직접 부딪히고 겪어보니 꼭 필요한 작업이라고 느꼈다. (물론 TDD는 나에겐 어려운 일이고 내가 논할 수준이 아직 아닌 거 같다고 느낀다)

이번 과제를 통해 함수를 잘게 쪼개는게 정말 중요하다고 느꼈고, 함수 단위 테스팅 또한 개발에 있어서 꼭 필요한 부분이라고 생각했다.
